//created on: 06/05/2019
package resources.rules.boards.arduino_climatizaion_boards

//list any import classes here.
import java.math.BigInteger;
import java.sql.Timestamp;
import java.util.List;
import br.com.vger.stufa.drools.DroolsActionHandler;
import br.com.vger.stufa.drools.EventHandler;
import br.com.vger.stufa.models.VgerSampling;
import br.com.vger.stufa.models.VgerModule
import br.com.vger.stufa.models.VgerSamplingSensor;
import br.com.vger.stufa.models.VgerSamplingActuator;
import br.com.vger.stufa.models.VgerSensor;
import br.com.vger.stufa.models.ClimatizationEventHandler;
import br.com.vger.stufa.models.ClimatizationEvent;

//declare any global variables here

global br.com.vger.stufa.drools.DroolsActionHandler drlActionHandler;

declare VgerSampling 
    @role( event )
end

declare VgerSamplingSensor 
 	sampling_uuid : Timestamp
 	sensor : VgerSensor 
	measure_type: String 
	value: Float
	rule_condition : Float
	created_at : Timestamp 
	updated_at : Timestamp 
end

declare ClimatizationEvent 
 	  module:VgerModule
	  sampling:VgerSampling
	  actuator_uuid: String 
	  actuator_active: Boolean
	  actuator_activated_time : BigInteger 
	  sensor_uuid:String
	  heat_index:Float
	  temperature:Float
	  humidity:Float
	  rule_condition_heat_index:Float
	  rule_condition_temperature:Float
	  rule_condition_humidity:Float
	  tmp_measure_type : String
end


rule "0101-climatization_actuation"
dialect "mvel"
//no-loop true
    when
		
		$climatization_event : ClimatizationEvent(
			$module: module,
			$sampling : sampling,
			$actuator_uuid : actuator_uuid,
			$actuator_active : actuator_active,
			$actuator_activated_time : actuator_activated_time,
			$sensor_uuid : sensor_uuid,
			$heat_index : heat_index,
			$temperature : temperature,
			$humidity : humidity
		) from entry-point "StufaClimatizationStream"
		
		//$module (name = "arduino_climatization_board#1")
		
		//if $climatization_event == hot / warm / cold (conjunto A B C)
		// check the actuators as well (actuator ON, OFF)
		
		//$actuator : VgerSamplingActuator(
		//	(active == false)
		//) from $actuators_status
		//eval($boards.size() > globalProperties.getTOTAL_CLIMATIZATION_BOARDS())
    then
    System.out.println("actuation: " + 
		"moduyle: "+$module+" "+
		"sampling: "+$sampling+" "+
		"actuator_uuid:"+$actuator_uuid+" "+
		"actuator_active:"+$actuator_active+" "+
		"actuator_activated_time:"+$actuator_activated_time+" "+
		"sensor_uuid: "+$sensor_uuid+" "+
		"heaT_index: "+$heat_index+" "+
		"temperature: "+$temperature+" "+
		"Humidity: "+$humidity+"");
    //$$climatization_event_handler.setLast_status_chage = Time();
    //$climatization_event_handler.setActuatorON($actuator);
end



/*
rule "Apply 10% discount to orders over US$ 100,00"
when
    $order : Order()
    $total : Number( doubleValue > 100 ) 
             from accumulate( OrderItem( order == $order, $value : value ),
                              init( double total = 0; ),
                              action( total += $value; ),
                              reverse( total -= $value; ),
                              result( total ) )
then
    # apply discount to $order
end
*/