//created on: 06/05/2019
package resources.rules.handlers

//list any import classes here.
import java.math.BigInteger;
import java.sql.Timestamp;
import br.com.vger.stufa.drools.DroolsActionHandler;
import br.com.vger.stufa.models.VgerSampling;
import br.com.vger.stufa.models.VgerSamplingSensor;
import br.com.vger.stufa.models.VgerSamplingActuator;
import br.com.vger.stufa.models.VgerSensor;
import br.com.vger.stufa.models.RuleEvent;

//declare any global variables here

global br.com.vger.stufa.drools.DroolsActionHandler drlActionHandler;

declare RuleEvent 
    @role( event )
end

declare RuleEvent 
	  rule_package:String
	  rule_name:String
	  value:Float
	  rule_condition:Float
	  cause_description:String
	  command:String
	  command_value:boolean
	  created_at:Timestamp
	  updated_at:Timestamp
	  sensor_uuid:String
	  actuator_uuid:String
	  sampling:VgerSampling
end


/*rule "001-dispatch_event" salience 10
dialect "mvel"
    when
    	$eventHandler : EventHandler($events_map : ruleEvents)
    	$ev : RuleEvent($) from $events
    then
			
		if(drlActionHandler.checkPreviousEvent(ev)) {
	        drlActionHandler.dispatchEvent(ev);
        }
end*/
