//created on: 06/05/2019
package resources.rules.boards.arduino_cliematizaion_boards

//list any import classes here.
import java.math.BigInteger;
import java.sql.Timestamp;
import java.util.List;
import br.com.sintechs.stufa.drools.DroolsActionHandler;
import br.com.sintechs.stufa.models.SintechsSampling;
import br.com.sintechs.stufa.models.SintechsSamplingSensor;
import br.com.sintechs.stufa.models.SintechsSamplingActuator;
import br.com.sintechs.stufa.models.SintechsSensor;
import br.com.sintechs.stufa.models.RuleEvent;

//declare any global variables here

global br.com.sintechs.stufa.drools.DroolsActionHandler drlActionHandler;

declare SintechsSampling 
    @role( event )
end

declare SintechsSamplingSensor 
 	sampling_uuid : Timestamp
 	sensor : SintechsSensor 
	measure_type: String 
	value: Float
	rule_condition : Float
	created_at : Timestamp 
	updated_at : Timestamp 
end


rule "004-climatization_actuation"
dialect "mvel"
//no-loop true
    when
		$eventHandler : EventHandler()
		$climatization_event_handler: ClimatizationEventHandler (
			$rule_event_list : rule_event_list,
			$boards : boards,
			$globalProperties : globalProperties
			$actuators_status : actuator_status
			$actuators_status_time : actuator_status_time
		) from entry-point "StufaClimatizationStream"
		
		
		$rule_event : RuleEvent(
			$event_value : value
			$rule_condition : rule_condition
			$actuator_uuid : actuator_uuid
		) from $rule_event_list
		
		$actuator : SintechsSamplingActuator(
			(active == false)
		) from $actuators_status
		//eval($boards.size() > globalProperties.getTOTAL_CLIMATIZATION_BOARDS())
    then
    //$$climatization_event_handler.setLast_status_chage = Time();
    $climatization_event_handler.setActuatorON($actuator);
end



rule "005-test1_climatization_actuation"
dialect "mvel"
//no-loop true
    when
		$eventHandler : EventHandler()
		$climatization_event_handler: ClimatizationEventHandler (
			$rule_event_list : rule_event_list,
			$boards : boards,
			$globalProperties : globalProperties
			$actuators_status : actuator_status
			$actuators_status_time : actuator_status_time
		) from entry-point "StufaClimatizationStream"
		
		
		$rule_event : RuleEvent(
			$event_value : value
			$rule_condition : rule_condition
			$actuator_uuid : actuator_uuid
		) from $rule_event_list
		
		$actuator : SintechsSamplingActuator(
			(active == false)
		) from $actuators_status
		//eval($boards.size() > globalProperties.getTOTAL_CLIMATIZATION_BOARDS())
    then
    //$$climatization_event_handler.setLast_status_chage = Time();
    $climatization_event_handler.setActuatorON($actuator);
end
/*
rule "Apply 10% discount to orders over US$ 100,00"
when
    $order : Order()
    $total : Number( doubleValue > 100 ) 
             from accumulate( OrderItem( order == $order, $value : value ),
                              init( double total = 0; ),
                              action( total += $value; ),
                              reverse( total -= $value; ),
                              result( total ) )
then
    # apply discount to $order
end
*/