//created on: 06/05/2019
package resources.rules.actuators

//list any import classes here.
import java.math.BigInteger;
import java.sql.Timestamp;
import br.com.sintechs.stufa.models.SintechsSampling;
import br.com.sintechs.stufa.models.SintechsSamplingSensor;
import br.com.sintechs.stufa.models.SintechsSamplingActuator;
import br.com.sintechs.stufa.models.SintechsSensor;
import br.com.sintechs.stufa.drools.DroolsActionHandler;
//declare any global variables here

global br.com.sintechs.stufa.drools.DroolsActionHandler drlActionHandler;

declare SintechsSampling 
    @role( event )
end

declare SintechsSamplingSensor 
 	sampling_id : BigInteger
 	sensor : SintechsSensor 
	measure_type: String 
	value: Float
	created_at : Timestamp 
	updated_at : Timestamp 
end


rule "001-max-heat_index"
dialect "mvel"
    when
    	//This is for test propouse, the rule must fire with this eval
    	//eval(1 == 1)
//        SintechsSampling($sensors_sampling : samplingSensors) from entry-point StufaSampingStream
		SintechsSampling($sensors_sampling : samplingSensors) 
        SintechsSamplingSensor(measure_type == "heat_index") from $sensors_sampling
    then
    	//System.out.println("Ligar Solenoid #1");
        //DroolsActionHandler.addAlert("Ligar Solenoid #1");
        drlActionHandler.addAlert("Turn On Solenoid #1");

end