//created on: 06/05/2019
package resources.rules.sensors.arduino_board_01

//list any import classes here.
import java.math.BigInteger;
import java.sql.Timestamp;
import br.com.sintechs.stufa.drools.DroolsActionHandler;
import br.com.sintechs.stufa.models.SintechsSampling;
import br.com.sintechs.stufa.models.SintechsSamplingSensor;
import br.com.sintechs.stufa.models.SintechsSamplingActuator;
import br.com.sintechs.stufa.models.SintechsSensor;
import br.com.sintechs.stufa.models.RuleEvent;

//declare any global variables here

global br.com.sintechs.stufa.drools.DroolsActionHandler drlActionHandler;

declare SintechsSampling 
    @role( event )
end

declare SintechsSamplingSensor 
 	sampling_id : BigInteger
 	sensor : SintechsSensor 
	measure_type: String 
	value: Float
	rule_condition : Float
	created_at : Timestamp 
	updated_at : Timestamp 
end


rule "001-max-heat_index-arduino_board_01"
dialect "mvel"
    when
    	//This is for test propouse, the rule must fire with this eval
    	//eval(1 == 1)
        //SintechsSampling($sensors_sampling : samplingSensors) from entry-point StufaSampingStream
		
		$sampling: SintechsSampling($sensors_sampling : samplingSensors) 
        $s : SintechsSamplingSensor(measure_type == "heat_index" && value > rule_condition) from $sensors_sampling
    then
        RuleEvent ev = new RuleEvent(drools.getRule().getName(),  $s.value, $s.rule_condition, $s.sampling_id,
			"[arduino_board#1.DTH11#1] Sensação Térmica acima da condição empregada",
			"solenoid_1", true, "DTH11#1", "solenoid#1");
			
		if(drlActionHandler.checkPreviousEvent(ev)) {
	        drlActionHandler.dispatchEvent(ev);
        }
end
/*
rule "002-max-temperature-arduino_board_01"
dialect "mvel"
    when
    	//This is for test propouse, the rule must fire with this eval
    	//eval(1 == 1)
        //SintechsSampling($sensors_sampling : samplingSensors) from entry-point StufaSampingStream
		
		SintechsSampling($sensors_sampling : samplingSensors) 
        $s : SintechsSamplingSensor(measure_type == "temperature" && value > rule_condition) from $sensors_sampling
    then
    	//System.out.println("Ligar Solenoid #1");
        //DroolsActionHandler.addAlert("Ligar Solenoid #1");
        RuleEvent ev = new RuleEvent(drools.getRule().getName(), $s.value,  $s.rule_condition, $s.sampling_id,
			$s.id, "[arduino_board#1.DTH11#1] Temperatura acima da condição empregada","solenoid_1", true, "DTH11#1", "solenoid#1");
		if(drlActionHandler.checkPreviousEvent(ev)) {
	        drlActionHandler.dispatchEvent(ev);
        }
end

rule "003-min-humidity-arduino_board_01"
dialect "mvel"
    when
    	//This is for test propouse, the rule must fire with this eval
    	//eval(1 == 1)
        //SintechsSampling($sensors_sampling : samplingSensors) from entry-point StufaSampingStream
		
		SintechsSampling($sensors_sampling : samplingSensors) 
        $s : SintechsSamplingSensor(measure_type == "humidity" && value < rule_condition) from $sensors_sampling
    then
         RuleEvent ev = new RuleEvent(drools.getRule().getName(),  $s.value,  $s.rule_condition, $s.sampling_id,
			$s.id, "[arduino_board#1.DTH11#1] Humidade abaixo da condição empregada","solenoid_1", true, "DTH11#1", "solenoid#1");
			
		if(drlActionHandler.checkPreviousEvent(ev)) {
	        drlActionHandler.dispatchEvent(ev);
	    }
end

rule "001-NOT-max-heat_index-arduino_board_01"
dialect "mvel"
    when
    	//This is for test propouse, the rule must fire with this eval
    	//eval(1 == 1)
        //SintechsSampling($sensors_sampling : samplingSensors) from entry-point StufaSampingStream
		
		SintechsSampling($sensors_sampling : samplingSensors) 
        $s : SintechsSamplingSensor(measure_type == "heat_index" && value <= rule_condition) from $sensors_sampling
    then
    	
        RuleEvent ev = new RuleEvent(drools.getRule().getName(),  $s.value, $s.rule_condition, $s.sampling_id,
			$s.id, "[arduino_board#1.DTH11#1] Sensação Térmica abaixo da condição empregada","solenoid_1", false, "DTH11#1", "solenoid#1");
			
		if(drlActionHandler.checkPreviousEvent(ev)) {
	        drlActionHandler.dispatchEvent(ev);
        }
end

rule "002-NOT-max-temperature-arduino_board_01"
dialect "mvel"
    when
    	//This is for test propouse, the rule must fire with this eval
    	//eval(1 == 1)
        //SintechsSampling($sensors_sampling : samplingSensors) from entry-point StufaSampingStream
		
		SintechsSampling($sensors_sampling : samplingSensors) 
        $s : SintechsSamplingSensor(measure_type == "temperature" && value <= rule_condition) from $sensors_sampling
    then
    	//System.out.println("Ligar Solenoid #1");
        //DroolsActionHandler.addAlert("Ligar Solenoid #1");
        RuleEvent ev = new RuleEvent(drools.getRule().getName(),  $s.value,  $s.rule_condition, $s.sampling_id,
			$s.id, "[arduino_board#1.DTH11#1] Temperatura abaixo da condição empregada","solenoid_1", false, "DTH11#1", "solenoid#1");
		if(drlActionHandler.checkPreviousEvent(ev)) {
	        drlActionHandler.dispatchEvent(ev);
        }
end

rule "003-NOT-min-humidity-arduino_board_01"
dialect "mvel"
    when
    	//This is for test propouse, the rule must fire with this eval
    	//eval(1 == 1)
        //SintechsSampling($sensors_sampling : samplingSensors) from entry-point StufaSampingStream
		
		SintechsSampling($sensors_sampling : samplingSensors) 
        $s : SintechsSamplingSensor(measure_type == "humidity" && value >= rule_condition) from $sensors_sampling
    then
         RuleEvent ev = new RuleEvent(drools.getRule().getName(),  $s.value,  $s.rule_condition, $s.sampling_id,
			$s.id, "[arduino_board#1.DTH11#1] Humidade acima da condição empregada","solenoid_1", false, "DTH11#1", "solenoid#1");
		if(drlActionHandler.checkPreviousEvent(ev)) {
	        drlActionHandler.dispatchEvent(ev);
        }
end
*/